-- Migration Script 003: Populate Countries
-- Purpose: Insert African countries
-- Run this script after 001 and 002

INSERT INTO countries (name, iso_code, iso3_code, phone_code) VALUES
('Algeria', 'DZ', 'DZA', '+213'),
('Angola', 'AO', 'AGO', '+244'),
('Benin', 'BJ', 'BEN', '+229'),
('Botswana', 'BW', 'BWA', '+267'),
('Burkina Faso', 'BF', 'BFA', '+226'),
('Burundi', 'BI', 'BDI', '+257'),
('Cameroon', 'CM', 'CMR', '+237'),
('Cape Verde', 'CV', 'CPV', '+238'),
('Central African Republic', 'CF', 'CAF', '+236'),
('Chad', 'TD', 'TCD', '+235'),
('Comoros', 'KM', 'COM', '+269'),
('Congo', 'CG', 'COG', '+242'),
('Democratic Republic of the Congo', 'CD', 'COD', '+243'),
('Djibouti', 'DJ', 'DJI', '+253'),
('Egypt', 'EG', 'EGY', '+20'),
('Equatorial Guinea', 'GQ', 'GNQ', '+240'),
('Eritrea', 'ER', 'ERI', '+291'),
('Ethiopia', 'ET', 'ETH', '+251'),
('Gabon', 'GA', 'GAB', '+241'),
('Gambia', 'GM', 'GMB', '+220'),
('Ghana', 'GH', 'GHA', '+233'),
('Guinea', 'GN', 'GIN', '+224'),
('Guinea-Bissau', 'GW', 'GNB', '+245'),
('Ivory Coast', 'CI', 'CIV', '+225'),
('Kenya', 'KE', 'KEN', '+254'),
('Lesotho', 'LS', 'LSO', '+266'),
('Liberia', 'LR', 'LBR', '+231'),
('Libya', 'LY', 'LBY', '+218'),
('Madagascar', 'MG', 'MDG', '+261'),
('Malawi', 'MW', 'MWI', '+265'),
('Mali', 'ML', 'MLI', '+223'),
('Mauritania', 'MR', 'MRT', '+222'),
('Mauritius', 'MU', 'MUS', '+230'),
('Morocco', 'MA', 'MAR', '+212'),
('Mozambique', 'MZ', 'MOZ', '+258'),
('Namibia', 'NA', 'NAM', '+264'),
('Niger', 'NE', 'NER', '+227'),
('Nigeria', 'NG', 'NGA', '+234'),
('Rwanda', 'RW', 'RWA', '+250'),
('Sao Tome and Principe', 'ST', 'STP', '+239'),
('Senegal', 'SN', 'SEN', '+221'),
('Seychelles', 'SC', 'SYC', '+248'),
('Sierra Leone', 'SL', 'SLE', '+232'),
('Somalia', 'SO', 'SOM', '+252'),
('South Africa', 'ZA', 'ZAF', '+27'),
('South Sudan', 'SS', 'SSD', '+211'),
('Sudan', 'SD', 'SDN', '+249'),
('Swaziland', 'SZ', 'SWZ', '+268'),
('Tanzania', 'TZ', 'TZA', '+255'),
('Togo', 'TG', 'TGO', '+228'),
('Tunisia', 'TN', 'TUN', '+216'),
('Uganda', 'UG', 'UGA', '+256'),
('Zambia', 'ZM', 'ZMB', '+260'),
('Zimbabwe', 'ZW', 'ZWE', '+263');
